version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.6.15-management
    container_name: rabbit-mq
    environment:
       RABBITMQ_DEFAULT_USER: user
       RABBITMQ_DEFAULT_PASS: psw
    ports:
      - 15672:15672
      - 5672:5672

  web-api:
    depends_on:
      - rabbitmq
      - postgres
    container_name: web-api
    build:
       context: .
       dockerfile: ./NMHAssignment.WebAPI/Dockerfile
    ports: 
       - "5000:8080"

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: psw
      POSTGRES_DB: postgresDb